### ISSUE TITLE
What do you think of merging it into video filter?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/tinymce_video_filter#3]
Fine if you prefer to keep it separate, but wondering what you think of merging it as a submodule of video_filter? The advantage is that it's then more obvious that there is TinyMCE support, just like there's CKEditor support (but not ckeditor5, :( ).

**Comment by indigoxela** [comment]
> wondering what you think of merging it as a submodule of video_filter

I think, that's actually a good idea. It doesn't even have to be a submodule, we could just merge the plugin with its hook. Not sure about the migration steps for existing users, though. (Only very few...)

Why I made it an extra module? I didn't want to annoy the Video Filter maintainer ( :wink: ) with yet more code to take care of, and I didn't know what you think about the whole TinyMCE thing, anyway.

**Comment by herbdool** [comment]
Pretty simple module so no big deal. Even better if you agree to become a co-maintainer of the video_filter module. :) We can put it in the same location as the ckeditor plugin, so I agree about not making it a submodule.
